- package-lock.json
- package.json
- src/components/GameFeatures/GameFeatures.jsx
- src/components/GameFeatures/GameFeatures.scss
- src/store/atoms.js
fixed the problems with toggles as an initial solution.
> fixed toggles

- src/components/QuizSection/Options/Options.jsx
- src/data/data.json
- src/store/atoms.js
- src/utils/questions.js
Just changed all the code that used game state to response to it correctly and the atom descriptions
> change name to Major-minor

- src/pages/Home/Home.jsx
- src/pages/Quiz/Overlay/Overlay.jsx
QuizState set to quiz instead of exit when user exit the game.
Now when user exit the game the exit overlay is gone when enter a new one
> update ovelay when exit

- src/components/QuizSection/QuizSection.jsx
Won't display affirmation  screen on hard level when success
> remove aff from hard

- src/pages/Home/Home.jsx
- src/pages/Home/Home.scss
1. Add media queries for the Home Page responsive screen, including the size and positions for 4 buttons, button text, the yellow guy size, and the text below the yellow guy.
2. Change the background position to fix to avoid the blank below the screen.
> add media queries for responsive screen

- src/pages/Welcome/Welcome.scss
make an animation for welcome screen
> Welcome Screen Animation

- src/components/GameFeatures/Timer/Timer.jsx
- src/components/QuizSection/QuizSection.scss
- src/pages/Game Finished/Dialogs/Dialogs.scss
- src/pages/Game Finished/Dialogs/ScoreDialog.jsx
- src/pages/Home/Home.scss
- src/store/atoms.js
2 task in 1 branch :
Time displayed in Game Finished
Text for Game Finished
> Text game finished

- src/pages/Home/Home.scss
Home page will display p element in white
> p element white color

- src/pages/Quiz/Affirmation/Affirmation.scss
> fix Affirmation Issue

- src/utils/questions.js
> Unique questions

- src/data/data.json
- src/pages/Quiz/Quiz.jsx
- src/utils/questions.js
the -1 is important in order to not removing unexisting index
> fix question img issue

- src/components/QuizSection/QuizSection.jsx
- src/pages/Quiz/QuizScreen/QuizScreen.jsx
changed the use memo dependencies array so it will load new questions when restart button is pressed + make the restart button visible again
> add use memo dependencies

- src/components/QuizSection/QuizSection.jsx
removed setQuestioNum(1) on fail case so it won't display the answer of question number 1 when fail on another question
> remove setQuestionNum on fail case

- src/pages/Quiz/QuizScreen/QuizScreen.scss
Updating sizes from the cat image
> Cat animation

- src/components/QuizSection/Options/IntervalOptions/IntervalOptions.jsx
- src/components/QuizSection/Options/KeyOptions/KeyOptions.jsx
- src/components/QuizSection/Options/Options.jsx
- src/components/QuizSection/QuizSection.jsx
- src/data/data.json
- src/pages/Home/Home.jsx
- src/pages/Home/Home.scss
- src/pages/Home/button.jsx
- src/utils/questions.js
- Added Interval identification button on home page
- Added Interval identification game mode
> added interval identification game mode

- src/components/QuizSection/Options/ChordOptions/ChordOptions.jsx
- src/components/QuizSection/Options/Options.jsx
- src/components/QuizSection/QuizSection.jsx
- src/pages/Home/Home.jsx
- src/utils/questions.js
> ChordOptions

- src/components/GameFeatures/GameFeatures.scss
- src/pages/Quiz/QuizScreen/QuizScreen.jsx
- src/pages/Quiz/QuizScreen/QuizScreen.scss
Implemented cheer up animation next to the cat that goes indefinite in the quiz section.
Dialogs phrases are:
Keep going!
You've got this!
Practice Makes Perfect!
> feat:added cheerup_animations

- package-lock.json
- package.json
- src/components/QuizSection/Options/LedgerOptions/LedgerOptions.jsx
- src/components/QuizSection/Options/Options.jsx
- src/components/QuizSection/QuizSection.jsx
- src/pages/Home/Home.jsx
- src/store/atoms.js
- src/utils/questions.js
1. add ledger button
2. add game mode
3. add corresponding notes from data.json file
> add ledger game mode

- src/data/data.json
- src/pages/Home/Home.scss
1. Fix interval game notes, M4s, and M5s to P4 (Perfect 4), and PR (Perfect 5).
2. Set the hard level to 10 easy, 10 medium, and 10 hard (requested from the Donovan) 
3. Slowed animation on the home page for the balls on bigger screens
> Fix interval answers note and add 10 questions to hard level

- src/components/QuizSection/Options/ScaleOptions/ScaleOptions.jsx
- src/pages/Quiz/QuizScreen/QuizScreen.scss
1. Fix the buttons layout, change the inline CSS for large button wrapper
**Now**
**Before**
2. Fix the validate props using propTypes
This is the error comes from the eslint, I have fixed this part.
> Scale identification buttons

- src/pages/Quiz/QuizScreen/QuizScreen.jsx
1. modified the scale page gameScreenStyle with inline css
2. modified the chord page gameScreenStyle with inline css
> scale and chord modified

- src/data/data.json
- src/utils/questions.js
- Changing the logical on the getRandomQuestions functions
- Now, if there are just few questions, the left questions will be randomized
> fix: random question functions

- src/App.jsx
- src/components/QuizSection/QuizSection.jsx
- src/store/atoms.js
When some one makes a question wrong and answers correctly after , score is not counted
> game Score logic updated

- src/utils/questions.js
Created a shuffling function for randomizing questions and removed redundant code for game == "key" condition as the while loop already fulfilled the case.
> updated questions.js to randomize questions

- src/pages/Quiz/QuizScreen/QuizScreen.scss
Added some speed to the dots/bubbles animation
> Slow dots animation

- src/data/chord.json
Added new svg questions in chord game
> chord game json update

- src/data/intervalIdentification.json
- src/data/noteIdentification.json
Easy 13-24 Medium 25-48 and Hard 29-55
> added new interval Identification questions
